// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaPK3V968MoJ-FbFkd_h2NESsu_eF-So',
    appId: '1:591957548638:android:54fede80b357ce994d9ecf',
    messagingSenderId: '591957548638',
    projectId: 'lets-chat-1c93d',
    storageBucket: 'lets-chat-1c93d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKwS1r6cUy0SA-VF9JmgMpad421O3Hrw',
    appId: '1:591957548638:ios:828afe0b6631a4a64d9ecf',
    messagingSenderId: '591957548638',
    projectId: 'lets-chat-1c93d',
    storageBucket: 'lets-chat-1c93d.appspot.com',
    androidClientId: '591957548638-d3m7lh5tq0p5rmoulcjajnselhn00bu0.apps.googleusercontent.com',
    iosClientId: '591957548638-euo4l3lqc27peivgmsutu0jssrsvp5n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );
}
